source 'https://github.com/CocoaPods/Specs.git'

target 'I17DirectionalProgressView', :exclusive => true do
  pod "I17DirectionalProgressView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "I17DirectionalProgressView", :path => "../"
end
