# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/I17DirectionalProgressView.xcworkspace -scheme I17DirectionalProgressView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
